### ISSUE TITLE
Não consigo executar nenhum código

### ISSUE THREAD

**Issue by rafaelgavarron** [DesignLiquido/visualg#11]
quando clico em executar e depurar dá: 'Error: Método não implementado'
o log com detalhes:

Error: Método não implementado.
	at InterpretadorMaplerComDepuracao2.visitarDeclaracaoCabecalhoPrograma (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:10108:15)
	at CabecalhoPrograma.aceitar (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:2775:26)
	at InterpretadorMaplerComDepuracao2.executar (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:16921:33)
	at InterpretadorMaplerComDepuracao2.executarUltimoEscopoComandoContinuar (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:16849:42)
	at InterpretadorMaplerComDepuracao2.instrucaoContinuarInterpretacao (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:16881:20)
	at DeleguaTempoExecucaoLocal.iniciar (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:104716:26)
	at DeleguaSessaoDepuracaoLocal.launchRequest (/home/rafaelgavarron/.vscode/extensions/designliquido.designliquido-vscode-0.12.8/dist/extensao.js:104939:32)

o código é este: 
![Imagem colada (2)](https://github.com/DesignLiquido/visualg/assets/59266460/b0b6cb19-2197-48f5-acd9-769d380ba816)

**Comment by leonelsanchesdasilva** [comment]
Este problema foi resolvido na versão 0.12.10 da extensão.

![image](https://github.com/DesignLiquido/visualg/assets/53848829/e22bb83a-a923-45d7-8c40-8bf01d3a16b0)
